### PR TITLE
Update for compatibility with rustc 1.3.0 nightly

### PR DESCRIPTION
**Pull request by kcking**
Let me know if you have any comments!

### CODE REVIEW

**Comment by generalelectrix** [comment]
Holy crap, you're amazing.  I set Rust aside for about a year until 1.0, and just the other day tried to port this and gave up after about 3 hours of pain.

Tests pass?

**Comment by kcking** [comment]
You're amazing for writing the library! :)

Yep all tests pass, including the send/recv test scripts. I haven't used the library in production yet though.

**Comment by generalelectrix** [comment]
Added you as a collaborator to this repo.  It'll be a bit before I move development of my current project back to Rust, so in the mean time I'm interested to hear your experiences if you use the library in production.

**Comment by kcking** [comment]
Sounds good!

**Pull request merged**
